version: "3.7"

services:
  app:
    build:
      context: src
    volumes:
      - ./data/secrets/:/secrets
    restart: unless-stopped
    environment:
      - NODE_ENV
      - SECRETS_DIR=/secrets
      - GOOGLE_API_KEY
      - PUBLIC_DOMAIN
      - REMOVE_SPONSORBLOCK_CATEGORIES
    labels:
      - "traefik.http.routers.ytcast.rule=Host(\"${PUBLIC_DOMAIN}\")"
      - "traefik.http.services.ytcast.loadbalancer.server.port=8080"
    init: true
    networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik
