version: "3.7"

services:
  app:
    build:
      context: src
    volumes:
      - type: volume
        source: yarn_cache
        target: /yarn-cache
      - ./data/secrets/:/secrets
    restart: unless-stopped
    environment:
      - NODE_ENV
      - SECRETS_DIR=/secrets
      - GOOGLE_API_KEY
    labels:
      - "traefik.http.routers.ytcast.rule=Host(\"${PUBLIC_DOMAIN}\")"
      - "traefik.http.services.ytcast.loadbalancer.server.port=8080"
    init: true
    networks:
      - traefik

volumes:
  yarn_cache:

networks:
  traefik:
    external:
      name: traefik
